// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbLSx6r9GwPpeJv9xbtX6pmrRKXepPdwE',
    appId: '1:981641180238:web:697f7dfe12033497623f1f',
    messagingSenderId: '981641180238',
    projectId: 'quizclassroomapp',
    authDomain: 'quizclassroomapp.firebaseapp.com',
    storageBucket: 'quizclassroomapp.firebasestorage.app',
    measurementId: 'G-TVWBZSJZ7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqYzg9HvFZXawWZClior-vceMZeQXywX4',
    appId: '1:981641180238:android:8eb9745ab089007e623f1f',
    messagingSenderId: '981641180238',
    projectId: 'quizclassroomapp',
    storageBucket: 'quizclassroomapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5y6Ywbr0VkxrNcoIDoPYkERD7gO3B-AM',
    appId: '1:981641180238:ios:cc055fbb0e069197623f1f',
    messagingSenderId: '981641180238',
    projectId: 'quizclassroomapp',
    storageBucket: 'quizclassroomapp.firebasestorage.app',
    iosBundleId: 'com.example.quizClassApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5y6Ywbr0VkxrNcoIDoPYkERD7gO3B-AM',
    appId: '1:981641180238:ios:cc055fbb0e069197623f1f',
    messagingSenderId: '981641180238',
    projectId: 'quizclassroomapp',
    storageBucket: 'quizclassroomapp.firebasestorage.app',
    iosBundleId: 'com.example.quizClassApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbLSx6r9GwPpeJv9xbtX6pmrRKXepPdwE',
    appId: '1:981641180238:web:0e7504b49373e25d623f1f',
    messagingSenderId: '981641180238',
    projectId: 'quizclassroomapp',
    authDomain: 'quizclassroomapp.firebaseapp.com',
    storageBucket: 'quizclassroomapp.firebasestorage.app',
    measurementId: 'G-CMKZ46PDE2',
  );
}
